server:
  port: 8082
spring:
  application:
    name: upload-service
  servlet:
    multipart:
      max-file-size: 5MB # Limit the size of file uploads
  datasource:
    url: jdbc:mysql://localhost:3306/cloudshopping
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
# Eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image: # Thumbnail
    width: 60
    height: 60
  tracker-list: # tracker Address
    - 192.168.112.101:22122
ly:
  upload:
    baseUrl: http://image.cloudshopping.com/
    allowTypes:
      - image/jpeg
      - image/png
      - image/bmp