server:
  port: 8089
spring:
  application:
    name: order-service
  redis:
    host: 127.0.0.1 #default port 6379
  datasource:
    url: jdbc:mysql://localhost:3306/cloudshopping?useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: shop1234
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
      host: 127.0.0.1
      username: guest
      password: guest
      virtual-host: /cloudshopping
      template:
        retry:
          enabled: true
          initial-interval: 10000ms
          max-interval: 30000ms
          multiplier: 2
        exchange: ly.item.exchange
      publisher-confirms: true
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
      prefer-ip-address: true
      ip-address: 127.0.0.1
mybatis:
  type-aliases-package: com.cloudshopping.item.pojo
  mapper-locations: mapper/OrderMapper.xml
  configuration:
    map-underscore-to-camel-case: true
mapper:
  not-empty: false
  identity: mysql
cloudshopping:
  jwt:
    pubKeyPath: /Users/limeizheng/Desktop/shop-v20/rsa.pub  # 公钥地址
    cookieName: CS_TOKEN
  worker:
    workerId: 1
    dataCentered: 1
