server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    virtual-host: /cloudshopping
  redis:
    #数据库索引
    database: 0
    host: 192.168.112.101
    port: 6379
    password:
  datasource:
    url: jdbc:mysql://localhost:3306/cloudshopping
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
#
#sms:
#    accessKeyId: YourId
#    accessKeySecret: YourSecret
#    signName: Cloud
#    verifyCodeTemplate: YourCode