server:
  port: 8084
spring:
  application:
    name: goods-page
  rabbitmq:
    host: 192.168.112.101
    username: cloudshopping
    password: cloudshopping
    virtual-host: /cloudshopping
  datasource:
    url: jdbc:mysql://localhost:3306/cloudshopping
    username: root
    password: root
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
  thymeleaf:
    cache: false
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000